/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pvporbit_freetype_FreeType */

#ifndef _Included_com_pvporbit_freetype_FreeType
#define _Included_com_pvporbit_freetype_FreeType
#ifdef __cplusplus
extern "C" {
#endif
#undef com_pvporbit_freetype_FreeType_FT_LOAD_DEFAULT
#define com_pvporbit_freetype_FreeType_FT_LOAD_DEFAULT 0L
#undef com_pvporbit_freetype_FreeType_FT_LOAD_NO_SCALE
#define com_pvporbit_freetype_FreeType_FT_LOAD_NO_SCALE 1L
#undef com_pvporbit_freetype_FreeType_FT_LOAD_NO_HINTING
#define com_pvporbit_freetype_FreeType_FT_LOAD_NO_HINTING 2L
#undef com_pvporbit_freetype_FreeType_FT_LOAD_RENDER
#define com_pvporbit_freetype_FreeType_FT_LOAD_RENDER 4L
#undef com_pvporbit_freetype_FreeType_FT_LOAD_NO_BITMAP
#define com_pvporbit_freetype_FreeType_FT_LOAD_NO_BITMAP 8L
#undef com_pvporbit_freetype_FreeType_FT_LOAD_VERTICAL_LAYOUT
#define com_pvporbit_freetype_FreeType_FT_LOAD_VERTICAL_LAYOUT 16L
#undef com_pvporbit_freetype_FreeType_FT_LOAD_FORCE_AUTOHINT
#define com_pvporbit_freetype_FreeType_FT_LOAD_FORCE_AUTOHINT 32L
#undef com_pvporbit_freetype_FreeType_FT_LOAD_CROP_BITMAP
#define com_pvporbit_freetype_FreeType_FT_LOAD_CROP_BITMAP 64L
#undef com_pvporbit_freetype_FreeType_FT_LOAD_PEDANTIC
#define com_pvporbit_freetype_FreeType_FT_LOAD_PEDANTIC 128L
#undef com_pvporbit_freetype_FreeType_FT_LOAD_IGNORE_GLOBAL_ADVANCE_WIDTH
#define com_pvporbit_freetype_FreeType_FT_LOAD_IGNORE_GLOBAL_ADVANCE_WIDTH 512L
#undef com_pvporbit_freetype_FreeType_FT_LOAD_NO_RECURSE
#define com_pvporbit_freetype_FreeType_FT_LOAD_NO_RECURSE 1024L
#undef com_pvporbit_freetype_FreeType_FT_LOAD_IGNORE_TRANSFORM
#define com_pvporbit_freetype_FreeType_FT_LOAD_IGNORE_TRANSFORM 2048L
#undef com_pvporbit_freetype_FreeType_FT_LOAD_MONOCHROME
#define com_pvporbit_freetype_FreeType_FT_LOAD_MONOCHROME 4096L
#undef com_pvporbit_freetype_FreeType_FT_LOAD_LINEAR_DESIGN
#define com_pvporbit_freetype_FreeType_FT_LOAD_LINEAR_DESIGN 8192L
#undef com_pvporbit_freetype_FreeType_FT_LOAD_NO_AUTOHINT
#define com_pvporbit_freetype_FreeType_FT_LOAD_NO_AUTOHINT 32768L
#undef com_pvporbit_freetype_FreeType_FT_LOAD_COLOR
#define com_pvporbit_freetype_FreeType_FT_LOAD_COLOR 1048576L
#undef com_pvporbit_freetype_FreeType_FT_LOAD_COMPUTE_METRICS
#define com_pvporbit_freetype_FreeType_FT_LOAD_COMPUTE_METRICS 2097152L
/*
 * Class:     com_pvporbit_freetype_FreeType
 * Method:    FT_Init_FreeType
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_pvporbit_freetype_FreeType_FT_1Init_1FreeType
  (JNIEnv *, jclass);

/*
 * Class:     com_pvporbit_freetype_FreeType
 * Method:    FT_New_Memory_Face
 * Signature: (JLjava/nio/ByteBuffer;II)J
 */
JNIEXPORT jlong JNICALL Java_com_pvporbit_freetype_FreeType_FT_1New_1Memory_1Face
  (JNIEnv *, jclass, jlong, jobject, jint, jint);

/*
 * Class:     com_pvporbit_freetype_FreeType
 * Method:    FT_Set_Pixel_Sizes
 * Signature: (JFF)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pvporbit_freetype_FreeType_FT_1Set_1Pixel_1Sizes
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     com_pvporbit_freetype_FreeType
 * Method:    FT_Load_Char
 * Signature: (JCI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pvporbit_freetype_FreeType_FT_1Load_1Char
  (JNIEnv *, jclass, jlong, jchar, jint);

/*
 * Class:     com_pvporbit_freetype_FreeType
 * Method:    FT_Done_Face
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pvporbit_freetype_FreeType_FT_1Done_1Face
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_pvporbit_freetype_FreeType
 * Method:    newBuffer
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_pvporbit_freetype_FreeType_newBuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_pvporbit_freetype_FreeType
 * Method:    fillBuffer
 * Signature: ([BLjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_com_pvporbit_freetype_FreeType_fillBuffer
  (JNIEnv *, jclass, jbyteArray, jobject, jint);

/*
 * Class:     com_pvporbit_freetype_FreeType
 * Method:    deleteBuffer
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_pvporbit_freetype_FreeType_deleteBuffer
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
