/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pvporbit_freetype_FreeType_FT_Render_Mode */

#ifndef _Included_com_pvporbit_freetype_FreeType_FT_Render_Mode
#define _Included_com_pvporbit_freetype_FreeType_FT_Render_Mode
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
